### ISSUE TITLE
outputs/img2img-images/loopback-wave/2065768621/%d.png: No such file or directory

### ISSUE THREAD

**Issue by airborne-commando** [FizzleDorf/Loopback-Wave-for-A1111-Webui#1]
Hello, whenever I try to generate a animation I get this error;
`[image2 @ 0x5647ac150080] Could find no file with path 'outputs/img2img-images/loopback-wave/2065768621/%d.png' and index in the range 0-4
outputs/img2img-images/loopback-wave/2065768621/%d.png: No such file or directory`

I even point to where my ffmpeg is located and the issue still happens, current OS I am using is Linux and the distro is Arch on a AMD card RX 6700 12GB.

This is a fresh install.

**Comment by FizzleDorf** [comment]
I do notice the latest A1111 update uses dates to sort the outputs. I am looking into this and will be pushing the changes to main. I'll let you know here when they are implemented. Thanks for the heads up.

**Comment by airborne-commando** [comment]
I'd also let you know I was able to stitch a video together with just using blender's video editor for now, it was able output the requested images in the output folder.

I'll mark this as closed and resolved.

**Comment by FizzleDorf** [comment]
no worries, I did make the changes so all should be well after a quick pull. Take care.
